<?php
/* 🎬 EVENTOS DE CONVIVÊNCIA V2 — cenas, segredos, memória e fofocas. */

function ecDadosParticipante($jogadores, $nome) { foreach ($jogadores as $j) if (($j['nome'] ?? '') === $nome) return $j; return []; }
function ecFaixaRelacao($valor) { if ($valor >= 55) return 'muito_alta'; if ($valor >= 20) return 'alta'; if ($valor <= -55) return 'muito_baixa'; if ($valor <= -20) return 'baixa'; return 'neutra'; }
function ecRodadaAtual(){ return max(1,(int)($_SESSION['rodada']??1)); }
function ecGarantirMemoria(){ if(!isset($_SESSION['conhecimentos_jogador'])||!is_array($_SESSION['conhecimentos_jogador'])) $_SESSION['conhecimentos_jogador']=[]; if(!isset($_SESSION['fofocas_casa'])||!is_array($_SESSION['fofocas_casa'])) $_SESSION['fofocas_casa']=[]; }
function ecLimparMemoriaExpirada(){ ecGarantirMemoria(); $r=ecRodadaAtual(); foreach($_SESSION['conhecimentos_jogador'] as $i=>$c){ if(!empty($c['expira_rodada']) && (int)$c['expira_rodada']<$r) $_SESSION['conhecimentos_jogador'][$i]['expirado']=true; } $_SESSION['conhecimentos_jogador']=array_slice($_SESSION['conhecimentos_jogador'],-30); $_SESSION['fofocas_casa']=array_values(array_filter($_SESSION['fofocas_casa'],fn($f)=>(int)($f['expira_rodada']??$r)>=$r)); }
function ecRegistrarConhecimento($tipo,$titulo,$texto,$fonte,$confiabilidade='media',$expira=null,$meta=[]){ ecGarantirMemoria(); $r=ecRodadaAtual(); $chave=md5($tipo.'|'.$titulo.'|'.$texto.'|'.$r); foreach($_SESSION['conhecimentos_jogador'] as $c) if(($c['chave']??'')===$chave) return; $_SESSION['conhecimentos_jogador'][]=array_merge(['chave'=>$chave,'tipo'=>$tipo,'titulo'=>$titulo,'texto'=>$texto,'fonte'=>$fonte,'confiabilidade'=>$confiabilidade,'rodada'=>$r,'expira_rodada'=>$expira,'expirado'=>false,'descoberto_em'=>date('H:i')],$meta); }
function ecConhecimentosAtivos(){ ecLimparMemoriaExpirada(); return array_values(array_filter($_SESSION['conhecimentos_jogador']??[],fn($c)=>empty($c['expirado']))); }
function ecEscolherAlvoProvavel($jogadores,$npc,$meuNome){ $cand=[]; foreach($jogadores as $j){$n=$j['nome']??''; if(!$n||$n===$npc||!empty($j['eliminado']))continue; $score=function_exists('calcularRelacaoIA')?calcularRelacaoIA($jogadores,$npc,$n,$meuNome):0; $cand[]=['nome'=>$n,'score'=>$score];} if(!$cand)return null; usort($cand,fn($a,$b)=>$a['score']<=>$b['score']); return $cand[0]['nome']; }
function ecGerarSegredoReal($jogadores,$npc,$meuNome,$modo='ouvido'){
  $r=ecRodadaAtual(); $rel=(int)($_SESSION['relacoes_jogador'][$npc]??0); $alvo=ecEscolherAlvoProvavel($jogadores,$npc,$meuNome);
  $op=[]; if($alvo) $op[]=['tipo'=>'intencao_voto','titulo'=>'🎯 Intenção de voto','texto'=>"$npc está considerando $alvo como um dos seus alvos nesta rodada.",'expira'=>$r];
  if($rel>=20) $op[]=['tipo'=>'protecao','titulo'=>'🛡️ Sinal de proteção','texto'=>"$npc demonstra que prefere manter você fora da linha de fogo por enquanto.",'expira'=>$r];
  if($rel<=-20) $op[]=['tipo'=>'ameaca','titulo'=>'⚠️ Seu nome está no radar','texto'=>"$npc vê você como uma opção real de alvo nesta rodada.",'expira'=>$r];
  $dados=ecDadosParticipante($jogadores,$npc); if(!empty($dados['alianca'])) $op[]=['tipo'=>'alianca','titulo'=>'🤝 Movimento de aliança','texto'=>"$npc está articulando decisões com a aliança “{$dados['alianca']}”.",'expira'=>$r+1];
  if(!$op) $op[]=['tipo'=>'leitura','titulo'=>'👀 Leitura de jogo','texto'=>"$npc está sondando votos e ainda não parece ter uma decisão totalmente fechada.",'expira'=>$r];
  $s=$op[array_rand($op)]; $s['fonte']=$modo==='contado'?"Contado diretamente por $npc":"Ouvido por você sem $npc perceber"; $s['confiabilidade']=$modo==='contado'?'alta':'alta'; return $s;
}
function ecCriarFofoca(&$jogadores,$origem,$meuNome){ $s=ecGerarSegredoReal($jogadores,$origem,$meuNome,'contado'); $nomes=[]; foreach($jogadores as $j){$n=$j['nome']??'';if($n&&$n!==$origem&&$n!==$meuNome&&!empty($j['eliminado'])===false)$nomes[]=$n;} if(!$nomes)return; $receptor=$nomes[array_rand($nomes)]; $distorcida=random_int(1,100)<=24; $texto=$s['texto']; if($distorcida){$alvo=ecEscolherAlvoProvavel($jogadores,$receptor,$meuNome); if($alvo) $texto="$origem estaria muito inclinado(a) a mirar em $alvo nesta rodada.";} $_SESSION['fofocas_casa'][]=['origem'=>$origem,'portador'=>$receptor,'texto'=>$texto,'verdadeira'=>!$distorcida,'rodada'=>ecRodadaAtual(),'expira_rodada'=>ecRodadaAtual()]; }
function ecTalvezCircularFofocas(&$jogadores,$meuNome,$fase){ $ch='ec_fofoca_'.$fase.'_'.ecRodadaAtual(); if(!empty($_SESSION[$ch]))return; $_SESSION[$ch]=true; if(random_int(1,100)>45)return; $nomes=[]; foreach($jogadores as $j){$n=$j['nome']??'';if($n&&$n!==$meuNome&&empty($j['eliminado']))$nomes[]=$n;} if($nomes) ecCriarFofoca($jogadores,$nomes[array_rand($nomes)],$meuNome); }
function ecFofocaParaJogador($jogadores,$npc){ ecGarantirMemoria(); $poss=[]; foreach($_SESSION['fofocas_casa'] as $f) if(($f['portador']??'')===$npc)$poss[]=$f; return $poss?$poss[array_rand($poss)]:null; }

function ecBiblioteca() { return [
'muito_alta'=>[
['confidencia','🤫','Uma confidência só para você','QUARTO','{npc} espera a casa esvaziar e fala baixo: “Eu confio em você. Tem coisa de voto circulando e acho que você precisa saber.”',[['🤝 Ouvir e guardar o segredo',10,7,0,'segredo_contado'],['🎯 Perguntar diretamente pelo alvo',4,3,0,'segredo_contado'],['🤐 Não querer se envolver',-2,0,0,null]]],
['pacto','🤝','Pacto até mais longe','ACADEMIA','{npc} propõe que vocês se protejam nas próximas semanas e troquem informações antes das votações.',[['🤝 Fechar o pacto',12,8,0,'segredo_contado'],['🧠 Aceitar, mas sem prometer voto',5,2,0,null],['🚪 Recusar com cuidado',-6,-2,0,null]]],
['protecao','🛡️','Uma promessa de proteção','COZINHA','{npc} diz que, se ganhar poder, pretende proteger você. Em troca, quer saber se a proteção é recíproca.',[['❤️ Prometer reciprocidade',9,6,0,null],['🎯 Dizer que depende da semana',2,0,0,null],['🧊 Evitar compromisso',-5,-2,0,null]]]],
'alta'=>[
['sondagem','🧠','Hora de falar de jogo','VARANDA','{npc} se aproxima: “Quero entender seu jogo. Quem você acha que está se tornando perigoso aqui dentro?”',[['🎯 Abrir parte do seu jogo',7,4,0,'segredo_contado'],['🤐 Ser diplomático',2,1,0,null],['🔒 Não entregar informação',-3,-1,0,null]]],
['apoio','💙','Um conselho inesperado','SALA','{npc} percebe você pensativo(a) e diz: “Não deixa essa semana te desmontar. Você está melhor no jogo do que imagina.”',[['😊 Agradecer sinceramente',8,4,0,null],['🤝 Aproveitar para falar de estratégia',5,3,0,'segredo_contado'],['😶 Mudar de assunto',-2,0,0,null]]],
['voto','🗳️','Conversa sobre voto','QUARTO','{npc} pergunta discretamente se vocês deveriam alinhar o voto para não desperdiçar força na casa.',[['🤝 Topar conversar sobre nomes',7,5,0,'segredo_contado'],['🧠 Ouvir sem se comprometer',3,1,0,'segredo_contado'],['🚫 Dizer que vota sozinho(a)',-5,-2,0,null]]]],
'neutra'=>[
['aproximacao','👀','Uma chance de aproximação','COZINHA','{npc} fica sozinho(a) com você por alguns minutos. É uma oportunidade rara de quebrar o gelo.',[['💬 Puxar uma conversa pessoal',7,3,0,null],['🎮 Falar apenas do jogo',3,1,0,null],['🚶 Deixar o momento passar',0,0,0,null]]],
['termometro','🌡️','Medindo o terreno','SALA','{npc} pergunta como você está enxergando a casa e observa atentamente sua resposta.',[['😊 Responder com sinceridade',5,2,0,null],['🧠 Dar uma resposta calculada',2,0,0,null],['🤐 Não revelar nada',-2,0,0,null]]],
['favor','🥤','Um pequeno gesto','COZINHA','{npc} pede sua ajuda com uma tarefa da casa. Parece simples, mas convivência também constrói relações.',[['🤝 Ajudar sem pensar duas vezes',6,3,0,null],['🙂 Ajudar, mas manter distância',3,1,0,null],['🙄 Dizer que está ocupado(a)',-5,-2,0,null]]]],
'baixa'=>[
['indireta','😏','Uma indireta bem direta','COZINHA','{npc} comenta em voz alta que “tem gente que muda quando ganha poder” e olha diretamente para você.',[['💥 Perguntar se foi para você',-8,-2,2,null],['😏 Devolver outra indireta',-10,-3,3,null],['🧊 Ignorar completamente',1,0,0,null]]],
['cobranca','👀','Clima de desconfiança','SALA','{npc} te chama de lado: “Eu sinto que você fala uma coisa pra mim e outra para a casa.”',[['🗣️ Se explicar',3,2,0,null],['🔥 Rebater a acusação',-9,-3,2,null],['🚶 Encerrar a conversa',-4,-1,0,null]]],
['voto_tenso','🗳️','Seu nome entrou na conversa','ACADEMIA','{npc} admite que seu nome já apareceu em conversas de voto. O clima fica imediatamente pesado.',[['🧠 Perguntar quem falou',1,1,0,'segredo_contado'],['🔥 Cobrar lealdade',-8,-3,2,null],['🤐 Guardar a informação',2,1,0,'segredo_contado']]]],
'muito_baixa'=>[
['confronto','🔥','O clima finalmente explodiu','SALA','{npc} te confronta na frente de outras pessoas: “Você sabe muito bem por que eu não confio em você.”',[['💥 Bater de frente',-14,-5,4,null],['🧠 Responder sem perder a calma',-3,1,2,null],['🚶 Sair da discussão',0,0,-1,null]]],
['ameaca_voto','🎯','Alvo declarado','QUARTO','{npc} não tenta esconder: “Se depender de mim, seu nome vai aparecer no próximo Paredão.”',[['🔥 Dizer que o sentimento é recíproco',-12,-4,3,'ameaca_direta'],['😏 Mostrar que não está intimidado(a)',-6,-1,2,'ameaca_direta'],['🧊 Não alimentar a rivalidade',2,1,0,'ameaca_direta']]],
['acerto','⚡','Uma última chance de conversar','VARANDA','Depois de dias de tensão, {npc} pergunta se ainda existe alguma chance de vocês baixarem as armas.',[['🤝 Tentar uma trégua',10,5,0,null],['🧠 Aceitar apenas por estratégia',4,1,0,null],['🚫 Recusar a trégua',-8,-3,1,null]]]],
'festa'=>[
['pista','🥂','Papo no meio da pista','FESTA','{npc} te puxa para um canto entre uma música e outra: “Hoje eu queria esquecer o jogo, mas preciso saber se ainda posso confiar em você.”',[['❤️ Reafirmar a confiança',9,5,0,null],['🙂 Manter o papo leve',4,1,0,null],['🎯 Transformar em conversa de jogo',2,2,0,'segredo_contado']]],
['danca','💃','Um convite inesperado','PISTA','{npc} estende a mão e chama você para dançar. Algumas pessoas da casa percebem a aproximação.',[['💃 Aceitar e curtir',8,3,1,null],['😊 Dançar sem criar expectativas',4,1,0,null],['🙈 Recusar gentilmente',-3,0,0,null]]],
['festa_treta','🍹','Festa, bebida e tensão','PISTA','Uma provocação de {npc} atravessa a música. O assunto é jogo e claramente foi direcionado a você.',[['🔥 Responder na hora',-10,-3,4,null],['🧠 Cortar com elegância',-2,1,2,null],['🚶 Ir para outro canto',1,0,0,null]]],
['segredo','👂','Você ouviu seu nome...','QUARTO','Ao passar pelo quarto, você escuta {npc} falando seu nome em uma conversa estratégica. A pessoa ainda não percebeu que você está por perto.',[['🤫 Continuar ouvindo',0,2,0,'segredo_ouvido'],['🚪 Sair discretamente',1,0,0,null],['😳 Entrar e perguntar o que houve',-5,-2,2,null]]],
['madrugada','🌙','Conversa de madrugada','VARANDA','A festa já desacelerou quando {npc} senta ao seu lado: “Aqui dentro é difícil saber o que é jogo e o que é de verdade.”',[['❤️ Falar com sinceridade',10,5,0,null],['🤝 Falar sobre confiança',6,4,0,'fofoca'],['😶 Apenas ouvir',3,2,0,null]]]],
]; }
function ecTalvezGerar(&$jogadores,$meuNome,$fase){ ecLimparMemoriaExpirada(); if(!preg_match('/^interacoes_/',$fase)&&$fase!=='festa')return; ecTalvezCircularFofocas($jogadores,$meuNome,$fase); if(!empty($_SESSION['evento_convivencia_ativo']))return; $ch='ec_tentado_'.$fase.'_'.ecRodadaAtual(); if(!empty($_SESSION[$ch]))return; $_SESSION[$ch]=true; $chance=$fase==='festa'?72:42; if(random_int(1,100)>$chance)return; $cand=[]; foreach($jogadores as $j){$n=$j['nome']??'';if(!$n||$n===$meuNome||!empty($j['eliminado']))continue;$rel=(int)($_SESSION['relacoes_jogador'][$n]??0);$cand[]=[$n,$rel,max(2,abs($rel)+15)];} if(!$cand)return; $total=array_sum(array_column($cand,2));$r=random_int(1,max(1,$total));$esc=$cand[0];foreach($cand as $c){$r-=$c[2];if($r<=0){$esc=$c;break;}} [$npc,$rel]=$esc;$lib=ecBiblioteca();$grupo=$fase==='festa'?'festa':ecFaixaRelacao($rel);if($fase==='festa'&&$rel<=-25&&random_int(1,100)<=55)$evento=$lib['festa'][2];else $evento=$lib[$grupo][array_rand($lib[$grupo])]; $_SESSION['evento_convivencia_ativo']=['id'=>$evento[0],'icone'=>$evento[1],'titulo'=>$evento[2],'camera'=>$evento[3],'texto'=>str_replace('{npc}',$npc,$evento[4]),'opcoes'=>$evento[5],'npc'=>$npc,'fase'=>$fase,'relacao_antes'=>$rel]; }
function ecProcessarEscolha(&$jogadores,$meuNome,$indice){$e=$_SESSION['evento_convivencia_ativo']??null;if(!$e)return;$op=$e['opcoes'][$indice]??null;if(!$op)return;$npc=$e['npc'];$delta=(int)$op[1];$conf=(int)$op[2];$pop=(int)$op[3];$efeito=$op[4]??null;ajustarRelacaoJogador($npc,$delta);alterarAfinidade($jogadores,$npc,$meuNome,$delta,$delta<0?abs((int)round($delta/2)):0,$conf);if($pop&&function_exists('alterarPopularidadePublica'))alterarPopularidadePublica($jogadores,$meuNome,$pop,$pop,'reagiu a um momento marcante da convivência',true);$extra='';
 if($efeito==='segredo_contado'||$efeito==='segredo_ouvido'){ $s=ecGerarSegredoReal($jogadores,$npc,$meuNome,$efeito==='segredo_contado'?'contado':'ouvido'); ecRegistrarConhecimento($s['tipo'],$s['titulo'],$s['texto'],$s['fonte'],$s['confiabilidade'],$s['expira'],['envolvido'=>$npc]); $extra=' 🔐 Uma nova informação foi adicionada a “O que eu sei”.'; }
 elseif($efeito==='ameaca_direta'){ ecRegistrarConhecimento('ameaca','🎯 Alvo declarado',"$npc declarou diretamente que considera colocar seu nome no próximo Paredão.","Dito diretamente por $npc",'alta',ecRodadaAtual(),['envolvido'=>$npc]);$extra=' 🔐 Você guardou essa declaração na memória.'; }
 elseif($efeito==='fofoca'){ $f=ecFofocaParaJogador($jogadores,$npc); if($f){ecRegistrarConhecimento('fofoca','🗣️ Fofoca que chegou até você',$f['texto'],"Contada por $npc",'media',ecRodadaAtual(),['envolvido'=>$npc,'verdade_interna'=>$f['verdadeira']]);$extra=' 🗣️ Você ouviu uma fofoca — ela pode estar incompleta ou distorcida.';} else {$s=ecGerarSegredoReal($jogadores,$npc,$meuNome,'contado');ecRegistrarConhecimento($s['tipo'],$s['titulo'],$s['texto'],"Impressão compartilhada por $npc",'media',$s['expira'],['envolvido'=>$npc]);$extra=' 🔐 Você registrou essa leitura de jogo.';}}
 $msg=$delta>=7?"$npc gostou muito da sua reação.":($delta>0?"O clima com $npc melhorou.":($delta<=-7?"A tensão com $npc aumentou.":($delta<0?"$npc não gostou muito da sua resposta.":'Você preferiu não mexer nessa relação.')));$_SESSION['evento_convivencia_resultado']=['titulo'=>'Consequência da sua escolha','texto'=>$msg.$extra,'icone'=>$delta<0?'⚡':'✨','npc'=>$npc,'fase'=>$e['fase']];unset($_SESSION['evento_convivencia_ativo']);$_SESSION['jogadores']=$jogadores;}
